name: hive_quick
description: A lightweight, intuitive, offline-first storage library built on top of Hive with Mongoose-style API methods. #database #hive #localstorage #offline #nosql
version: 1.0.3
homepage: https://github.com/SamiUllahOfficiale/hive_quick
repository: https://github.com/SamiUllahOfficiale/hive_quick

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  flutter_secure_storage: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
